// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ClawCLose.h"
#include "Commands/ClawOpen.h"
#include "Commands/DriveBackward.h"
#include "Commands/DriveForward.h"
#include "Commands/ShiftBackward.h"
#include "Commands/ShiftDown.h"
#include "Commands/ShiftForward.h"
#include "Commands/ShiftUp.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystick1.reset(new frc::Joystick(0));
    
    lowerButton.reset(new frc::JoystickButton(joystick1.get(), 2));
    lowerButton->WhileHeld(new ShiftDown());
    raiseButton.reset(new frc::JoystickButton(joystick1.get(), 1));
    raiseButton->WhileHeld(new ShiftUp());

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("ClawCLose", new ClawCLose());
    frc::SmartDashboard::PutData("ClawOpen", new ClawOpen());
    frc::SmartDashboard::PutData("ShiftForward", new ShiftForward());
    frc::SmartDashboard::PutData("ShiftBackward", new ShiftBackward());
    frc::SmartDashboard::PutData("ShiftDown", new ShiftDown());
    frc::SmartDashboard::PutData("ShiftUp", new ShiftUp());
    frc::SmartDashboard::PutData("DriveBackward", new DriveBackward());
    frc::SmartDashboard::PutData("DriveForward", new DriveForward());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

double OI::getLeftAxis()
{
    return -joystick1->GetY();
}

double OI::getRightAxis()
{
     return joystick1->GetRawAxis(3);
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getJoystick1() {
   return joystick1;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
